#ifndef LEDRINGANIMATIONS_H
#define LEDRINGANIMATIONS_H

#include <Arduino.h>

enum ledRingAnimation {
    LEDRING_START_TIMER,
    LEDRING_STOP_TIMER,
    LEDRING_PAUSE_TIMER,
    LEDRING_FINISHED_TIMER,
    LEDRING_STARTUP,
    LEDRING_RETURN_MAIN_MENU,
    LEDRING_PREPARE_SLEEP,
    LEDRING_MODE_SELECT,
};

#endif