#ifndef SYSSTATE_H
#define SYSSTATE_H

enum SystemState {
    STATE_MODE_SELECT,

    STATE_WIFI_SELECT,

    STATE_TIMER_SELECT,
    STATE_TIMER_RUN,
    STATE_TIMER_PAUSED,
    STATE_TIMER_FINISHED,

    STATE_PULSE_SELECT,
    STATE_PULSE_RUN,

    STATE_SLEEP,
    STATE_PREPARE_SLEEP,
};

#endif